version: '3.6'

services:

  drupal:
    build: .
    depends_on:
      - db
    ports:
      - 8888:80
    volumes:
      # Mount the module Commerce Google Tag Manager in the proper contrib module directory.
      - .:/var/www/html/modules/contrib/commerce_google_tag_manager
    restart: unless-stopped

  db:
    image: mariadb:10.3.7
    environment:
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: root
    restart: unless-stopped
